runtime: python38
env: standard
service: default

instance_class: F1

automatic_scaling:
  min_instances: 1
  max_instances: 1

entrypoint: python bot.py

handlers:
- url: /.*
  secure: always
  script: auto

includes:
- secrets.yaml